### PR TITLE
Removed some mentions about deccomissioned freddy.

### PR DESCRIPTION
**Pull request by babdab9**
This pr fixes #407 in Fredrikam/fredboat **Link:https://github.com/Frederikam/FredBoat/issues/407**

@napstr you can now close it safely.

Greets from Greece!
-Player 1

### CODE REVIEW

**Comment by napstr** [comment]
This doesn't look right. Instead of removing the mentions this adds even more.

**Comment by napstr** [comment]
Can you explain your decision to leave the invite link to a decommissioned bot in there, when the task is to remove it?

**Comment by babdab9** [comment]
did I? where?

**Comment by babdab9** [comment]
dammit, lemme review this

**Comment by babdab9** [comment]
is there smth more I forgot? doesnt seem like it

**Pull request merged**
