### PR TITLE
fix: .snyk & package.json to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by shikhir-arora**
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/npm:hoek:20180212
- https://snyk.io/vuln/npm:npm:20180222

The following vulnerabilities are fixed with a Snyk patch:
- https://snyk.io/vuln/npm:hoek:20180212

--- 

Snyk is pretty neat 💯

### CODE REVIEW

**Comment by napstr** [comment]
What does dragging in the snyk dependency concretely do?

**Comment by shikhir-arora** [comment]
It's required for the pull; as part of the deploy snyk will run a test for any security issues, and (the way it's setup now) run `snyk protect` before deploying, applying any patches from the `.snyk` file. This can be automated, or one can run various CLI commands (monitor, audit, etc.) to manually check and update the `.snyk` patch file.

Here's the part from the deploy on Netlify:

```
11:22:40 AM: > npm run snyk-protect
11:22:40 AM: > docs.fredboat.com@0.1.0 snyk-protect /opt/build/repo
11:22:40 AM: > snyk protect
11:22:51 AM: Successfully applied Snyk patches
```

**Comment by napstr** [comment]
I don't fully understand why that is needed - shouldn't bumping the dependencies to safe versions be enough?

**Comment by shikhir-arora** [comment]
Yeah, kind of - it's a lot more work. This is a bit more specific - it's tracking all the dependencies and their dependencies and so on, and when there's a security fix, it'll apply a patch (literally a git patch) if need be. Sometimes repos don't actually publish to npm every time they have a security issue unless it's major. For example, there's tons of projects that will patch it in `master` and up the version sometime later. That's the only benefit here -- since these are pretty old, in this case - yes, but it's not always the case.

I use it automatically and it works well, since it's real-time patching.

**Comment by shikhir-arora** [comment]
You should probably just add Snyk to this repo, no point in me doing it since it should be automatic. I highly reccomend it 🙂 - closing this PR for now though. 

(also, @napstr - see the above commit for an example of what I meant in my last message 👍)

**Pull request closed without merging**
