### PR TITLE
Permission Ranks Table

### PR DESCRIPTION
**Pull request by TernundaHunter**
I have noticed people have been frequently confused by the permissions system the way it is laid out as the rank description is under the actual rank. So, I formatted them to be side by side in a table so it may be more easily understood. Included a quick refinement of the notes bullet including the default dj rank, and a quick grammar check at the end.

### CODE REVIEW

**Comment by Frederikam** [comment]
Looks like we have a CSS problem 
image

**Comment by Frederikam** [comment]
Preferably I would fix the CSS

**Comment by TernundaHunter** [comment]
Pushed a request to fix the code padding to 2px rather than 8px.

**Comment by napstr** [comment]
The code blocks/inlines still look slightly fucked up (for me), but this commit that is part of another PR will fix that:
https://github.com/FredBoat/fredboat.com/pull/14/commits/5a58431f4e6cb7e068acc5dd33ef69be6a21d4ca#diff-7f646c5c38bc161cb9d53a4646a4601eR19

**Pull request merged**
